# Generated by Django 4.1.7 on 2023-06-10 16:01

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [("occurrence", "0001_initial"), ("occurrence", "0002_occurrence")]

    initial = True

    dependencies = [
        ("species", "0001_initial"),
        ("stakeholder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BasisOfRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("sort_id", models.IntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Basis of record",
                "verbose_name_plural": "Basis of records",
                "db_table": "basis_of_record",
            },
        ),
        migrations.CreateModel(
            name="OccurrenceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Occurrence status",
                "verbose_name_plural": "Occurrence statuses",
                "db_table": "occurrence_status",
            },
        ),
        migrations.CreateModel(
            name="OrganismQuantityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("sort_id", models.IntegerField(unique=True)),
            ],
            options={
                "verbose_name": "organism_quantity_type",
                "verbose_name_plural": "organism_quantity_type",
                "db_table": "organism_quantity_type",
            },
        ),
        migrations.CreateModel(
            name="SamplingSizeUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=4, unique=True)),
            ],
            options={
                "verbose_name": "Sampling size unit",
                "verbose_name_plural": "Sampling size units",
                "db_table": "sampling_size_unit",
            },
        ),
        migrations.CreateModel(
            name="SurveyMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("sort_id", models.IntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Survey method",
                "verbose_name_plural": "Survey methods",
                "db_table": "survey_method",
            },
        ),
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("individual_count", models.IntegerField()),
                ("organism_quantity", models.IntegerField()),
                ("sampling_size_value", models.FloatField()),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                ("owner_institution_code", models.CharField(max_length=250)),
                ("coordinates_uncertainty_m", models.IntegerField()),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "basis_of_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="occurrence.basisofrecord",
                    ),
                ),
                (
                    "occurrence_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="occurrence.occurrencestatus",
                    ),
                ),
                (
                    "ogranism_quantity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="occurrence.organismquantitytype",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stakeholder.organisation",
                    ),
                ),
                (
                    "sampling_size_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="occurrence.samplingsizeunit",
                    ),
                ),
                (
                    "survey_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="occurrence.surveymethod",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="species.taxon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Occurrence",
                "verbose_name_plural": "Occurrences",
                "db_table": "occurrence",
            },
        ),
    ]
