# Generated by Django 4.1.7 on 2023-06-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasisOfRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("sort_id", models.IntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Basis of record",
                "verbose_name_plural": "Basis of records",
                "db_table": "basis_of_record",
            },
        ),
        migrations.CreateModel(
            name="OccurrenceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Occurrence status",
                "verbose_name_plural": "Occurrence statuses",
                "db_table": "occurrence_status",
            },
        ),
        migrations.CreateModel(
            name="OrganismQuantityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("sort_id", models.IntegerField(unique=True)),
            ],
            options={
                "verbose_name": "organism_quantity_type",
                "verbose_name_plural": "organism_quantity_type",
                "db_table": "organism_quantity_type",
            },
        ),
        migrations.CreateModel(
            name="SamplingSizeUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=4, unique=True)),
            ],
            options={
                "verbose_name": "Sampling size unit",
                "verbose_name_plural": "Sampling size units",
                "db_table": "sampling_size_unit",
            },
        ),
        migrations.CreateModel(
            name="SurveyMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("sort_id", models.IntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Survey method",
                "verbose_name_plural": "Survey methods",
                "db_table": "survey_method",
            },
        ),
    ]
