# Generated by Django 4.1.7 on 2023-06-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganismQuantityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("sort_id", models.IntegerField(unique=True)),
            ],
            options={
                "db_table": "organism_quantity_type",
            },
        ),
    ]
