# Generated by Django 4.1.7 on 2023-06-11 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0004_alter_organisationrepresentative_organisation_and_more"),
        ("species", "0002_alter_ownedspecies_count_method_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("occurrence", "0001_occurrence_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrence",
            name="basis_of_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="occurrence.basisofrecord",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="occurrence_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="occurrence.occurrencestatus",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="ogranism_quantity_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="occurrence.organismquantitytype",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stakeholder.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="sampling_size_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="occurrence.samplingsizeunit",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="survey_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="occurrence.surveymethod",
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="taxon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="species.taxon"
            ),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
