# Generated by Django 4.1.7 on 2023-06-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("occurrence", "0002_alter_occurrence_basis_of_record_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplingsizeunit",
            name="unit",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
