# Generated by Django 4.1.7 on 2023-06-06 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('occurrence', '0002_basis_of_record'),
        ('occurrence', '0002_occurrencestatus'),
        ('occurrence', '0002_samplingsizeunit'),
    ]

    operations = []
