# Generated by Django 4.1.7 on 2023-07-06 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("occurrence", "0003_alter_samplingsizeunit_unit"),
        ("occurrence", "0003_remove_occurrence_basis_of_record_and_more"),
    ]

    operations = []
