# Generated by Django 4.1.7 on 2023-05-24 15:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='RasterLayer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=15)),
                ('extent', models.CharField(max_length=20, null=True)),
                (
                    'srid',
                    models.CharField(default='4326', max_length=4, null=True),
                ),
                ('description', models.TextField(null=True)),
                (
                    'raster_file',
                    django.contrib.gis.db.models.fields.RasterField(
                        srid=4326
                    ),
                ),
            ],
            options={
                'verbose_name': 'Raster layer',
                'verbose_name_plural': 'Raster layers',
            },
        ),
        migrations.CreateModel(
            name='VectorLayer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=15)),
                ('extent', models.CharField(max_length=20, null=True)),
                (
                    'srid',
                    models.CharField(default='4326', max_length=4, null=True),
                ),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Vector layer',
                'verbose_name_plural': 'Vector layers',
            },
        ),
        migrations.CreateModel(
            name='WMS',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=15)),
                ('extent', models.CharField(max_length=20, null=True)),
                (
                    'srid',
                    models.CharField(default='4326', max_length=4, null=True),
                ),
                ('description', models.TextField(null=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'WMS',
                'verbose_name_plural': 'WMS',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'geom',
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=4326
                    ),
                ),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                (
                    'layer_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='sanbi_spatial_layers.vectorlayer',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
