# Generated by Django 4.1.7 on 2023-05-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ('sanbi_spatial_layers', '0001_initial'),
        ('sanbi_spatial_layers', '0002_alter_feature_layer_id'),
        ('sanbi_spatial_layers', '0003_alter_feature_layer_id'),
        (
            'sanbi_spatial_layers',
            '0004_remove_feature_layer_id_delete_rasterlayer_and_more',
        ),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='WMS',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=512)),
                ('type', models.CharField(max_length=15)),
                ('extent', models.CharField(max_length=20, null=True)),
                (
                    'srid',
                    models.CharField(default='4326', max_length=4, null=True),
                ),
                ('description', models.TextField(null=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'WMS',
                'verbose_name_plural': 'WMS',
            },
        ),
    ]
