# Generated by Django 4.1.7 on 2023-06-03 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0001_login_status_migration"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="loginstatus",
            table="login_status",
        ),
        migrations.AlterModelTable(
            name="usertitle",
            table="user_title",
        ),
    ]
