# Generated by Django 4.1.7 on 2023-06-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0003_userlogin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationrepresentative",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stakeholder.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="organisationuser",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stakeholder.organisation",
            ),
        ),
    ]
