# Generated by Django 4.1.7 on 2023-06-08 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0003_organization"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="data_use_permission_id",
            new_name="data_use_permission",
        ),
    ]
