# Generated by Django 4.1.7 on 2023-06-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "stakeholder",
            "0005_userprofile_picture_alter_userprofile_cell_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="title_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="stakeholder.usertitle",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_role_type_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="stakeholder.userroletype",
            ),
        ),
    ]
