# Generated by Django 4.1.7 on 2023-07-06 19:16
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stakeholder", "0006_alter_userprofile_title_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationInvites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stakeholder.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OrganisationInvites",
                "verbose_name_plural": "OrganisationInvites",
                "db_table": "OrganisationInvites",
            },
        ),
    ]
