# Generated by Django 4.1.7 on 2023-07-11 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0007_organisationinvites"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationinvites",
            name="assigned_as",
            field=models.CharField(
                choices=[("Member", "Member"), ("Manager", "Manager")],
                default="Member",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="organisationinvites",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="stakeholder.organisation",
            ),
        ),
    ]
