# Generated by Django 4.1.7 on 2023-07-19 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stakeholder", "0008_organisationinvites_assigned_as_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="received_notif",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Reminders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[("Personal", "Personal"), ("Everyone", "Everyone")],
                        default="Personal",
                        max_length=50,
                    ),
                ),
                ("reminder", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Draft", "Draft"),
                            ("Passed", "Passed"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("email_sent", models.BooleanField(default=False)),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="stakeholder.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder",
                "verbose_name_plural": "Reminders",
                "db_table": "Reminders",
            },
        ),
    ]
