# Generated by Django 4.1.10 on 2023-08-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0009_userprofile_received_notif_reminders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userroletype",
            name="name",
            field=models.CharField(
                choices=[
                    ("Super user", "Super user"),
                    ("Admin", "Admin"),
                    ("Decision maker", "Decision maker"),
                    ("Data contributor", "Data contributor"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
