# Generated by Django 4.1.10 on 2023-08-18 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0011_organisation_national_organisation_province"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="title_id",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="user_role_type_id",
            new_name="user_role_type",
        ),
    ]
