# Generated by Django 4.1.10 on 2023-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0012_userprofile_current_organisation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="allowing_sanbi_to_expose_data",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="hosting_through_sanbi_platforms",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="use_of_data_by_sanbi_only",
        ),
        migrations.AddField(
            model_name="organisation",
            name="allowing_sanbi_to_expose_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organisation",
            name="hosting_through_sanbi_platforms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organisation",
            name="use_of_data_by_sanbi_only",
            field=models.BooleanField(default=False),
        ),
    ]
