# Generated by Django 4.1.10 on 2023-09-24 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "stakeholder",
            "0013_remove_userprofile_allowing_sanbi_to_expose_data_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisationinvites",
            options={
                "permissions": [
                    (
                        "can_invite_people_to_organisation",
                        "Can invite people to organisation",
                    )
                ],
                "verbose_name": "OrganisationInvites",
                "verbose_name_plural": "OrganisationInvites",
            },
        ),
    ]
