# Generated by Django 4.1.10 on 2023-10-17 12:42

from django.db import migrations, models
from stakeholder.utils import forward_func_0015


def create_short_code(apps, schema_editor):
    Province = apps.get_model('property', 'Province')
    Organisation = apps.get_model('stakeholder', 'Organisation')

    forward_func_0015(Province, Organisation)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0014_alter_organisationinvites_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="short_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(create_short_code, reverse_func)
    ]
