# Generated by Django 4.1.10 on 2023-10-17 12:42

from django.db import migrations, models
from property.tasks import update_organisation_property_short_code
from stakeholder.utils import get_organisation_short_code


def create_short_code(apps, schema_editor):
    Province = apps.get_model('property', 'Province')
    Organisation = apps.get_model('stakeholder', 'Organisation')

    for province in Province.objects.all():
        update_organisation_property_short_code(
            province_id=province.id,
            update_organisation=True,
            update_property=False,
            ProvinceModel=Province,
            OrganisationModel=Organisation
        )

    for org in Organisation.objects.filter(province__isnull=True):
        short_code = get_organisation_short_code(
            province_name='',
            organisation_name=org.name,
            with_digit=True,
            OrganisationModel=Organisation
        )
        org.short_code = short_code
        org.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0014_alter_organisationinvites_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="short_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(create_short_code, reverse_func)
    ]
