# Generated by Django 4.1.10 on 2023-11-15 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0011_alter_property_created_by_and_more"),
        ("regulatory_permit", "0001_data_use_permit_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stakeholder", "0015_organisation_short_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="data_use_permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="regulatory_permit.datausepermission",
            ),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="property.province",
            ),
        ),
        migrations.AlterField(
            model_name="organisationinvites",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stakeholder.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="organisationinvites",
            name="user_role",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stakeholder.userroletype",
            ),
        ),
        migrations.AlterField(
            model_name="reminders",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stakeholder.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="reminders",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="login_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stakeholder.loginstatus",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="title_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stakeholder.usertitle",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_role_type_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stakeholder.userroletype",
            ),
        ),
    ]
