# Generated by Django 4.1.13 on 2023-12-01 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stakeholder", "0016_alter_organisation_data_use_permission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationinvites",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organisationinvites",
            name="uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
