# Generated by Django 4.1.13 on 2023-12-11 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0017_organisationinvites_user_organisationinvites_uuid"),
    ]

    operations = [
        # this is to make this migration reversible
        # note: ensure there is a record in datausepermission table
        migrations.AlterField(
            model_name='organisation',
            name='data_use_permission',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="regulatory_permit.datausepermission",
                default=1
            )
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="data_use_permission",
        ),
    ]
