# Generated by Django 4.1.13 on 2023-12-01 03:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0017_organisationinvites_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationinvites",
            name="invitation_uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
