# Generated by Django 4.1.13 on 2023-12-01 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0018_organisationinvites_invitation_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisationinvites",
            old_name="invitation_uuid",
            new_name="uuid",
        ),
    ]
