CSV_FILE_HEADERS = [
    "Property_name",
    "Scientific_name",
    "Common_name_verbatim",
    "open/close_system",
    "presence/absence",
    "Year of estimate",
    "COUNT_TOTAL",
    "Count_adult_males",
    "Count_adult_females",
    "COUNT_subadult_TOTAL",
    "Count_subadult_male",
    "Count_subadult_female",
    "COUNT_Juvenile_TOTAL",
    "Count_Juvenile_males",
    "Count_Juvenile_females",
    "No. subpopulations / groups",
    "Area_available to population (total enclosure area)_ha",
    "Population_status",
    "Population estimate category",
    "If other (population estimate category) , please explain",
    "Survey_method",
    "If other (survey method), please explain",
    "Sampling_effort_coverage",
    "Population estimate certainty",
    "Upper confidence limits for population estimate",
    "Lower confidence limits for population estimate",
    "Certainity of population bounds",
    "(Re)Introduction_TOTAL",
    "(Re)Introduction_adult_males",
    "(Re)Introduction_adult_females",
    "(Re)Introduction_male_juveniles",
    "(Re)Introduction_female_juveniles",
    "Founder population?",
    "(Re)Introduction_source",
    "Permit_number (if applicable)",
    "Offtake_TOTAL",
    "Translocation_offtake_total",
    "Translocation_Offtake_adult_males",
    "Translocation_Offtake_adult_females",
    "Translocation_Offtake_male_juveniles",
    "Translocation_Offtake_female_juveniles",
    "Translocation_destination",
    "Translocation_Offtake_Permit_number",
    "Planned hunt/culling_TOTAL",
    "Planned hunt/culling_Offtake_adult_males",
    "Planned hunt/culling_Offtake_adult_females",
    "Planned hunt/culling_Offtake_male_juveniles",
    "Planned hunt/culling_Offtake_female_juveniles",
    "Planned hunt/culling_Permit_number",
    "Planned euthanasia_TOTAL",
    "Planned euthanasia_Offtake_adult_males",
    "Planned euthanasia_Offtake_adult_females",
    "Planned euthanasia_Offtake_male_juveniles",
    "Planned euthanasia_Offtake_female_juveniles",
    "Planned euthanasia_Permit_number",
    "Unplanned/illegal hunting_TOTAL",
    "Unplanned/illegal hunting_Offtake_adult_males",
    "Unplanned/illegal hunting_Offtake_adult_females",
    "Unplanned/illegal hunting_Offtake_male_juveniles",
    "Unplanned/illegal hunting_Offtake_female_juveniles"
]
