# Generated by Django 4.1.7 on 2023-06-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CountMethod',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'count method',
                'verbose_name_plural': 'count methods',
                'db_table': 'count_method',
            },
        ),
    ]