# Generated by Django 4.1.7 on 2023-06-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='NatureOfPopulation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
                ('extensive', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Nature of Population',
                'verbose_name_plural': 'Nature of Population',
                'db_table': 'nature_of_population',
            },
        ),
    ]
