# Generated by Django 4.1.7 on 2023-06-12 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0002_alter_ownedspecies_count_method_and_more"),
        ("activity", "0001_initial"),
        ("population_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationCountPerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.DateField()),
                ("total", models.IntegerField()),
                ("adult_male", models.IntegerField(blank=True, null=True)),
                ("adult_female", models.IntegerField(blank=True, null=True)),
                ("juvenile_male", models.IntegerField(blank=True, null=True)),
                ("juvenile_female", models.IntegerField(blank=True, null=True)),
                ("founder_population", models.BooleanField(blank=True, null=True)),
                (
                    "reintroduction_source",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("permit_number", models.IntegerField(blank=True, null=True)),
                (
                    "activity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activity.activitytype",
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="population_data.month",
                    ),
                ),
                (
                    "owned_species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="species.ownedspecies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Population count per activities",
                "db_table": "population_count_per_activity",
                "unique_together": {("year", "owned_species", "activity_type")},
            },
        ),
        migrations.CreateModel(
            name="PopulationCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.DateField()),
                ("total", models.IntegerField()),
                ("adult_male", models.IntegerField(blank=True, null=True)),
                ("adult_female", models.IntegerField(blank=True, null=True)),
                ("juvenile_male", models.IntegerField(blank=True, null=True)),
                ("juvenile_female", models.IntegerField(blank=True, null=True)),
                ("sub_adult_total", models.IntegerField(blank=True, null=True)),
                ("sub_adult_male", models.IntegerField(blank=True, null=True)),
                ("sub_adult_female", models.IntegerField(blank=True, null=True)),
                ("juvenile_total", models.IntegerField(blank=True, null=True)),
                ("pride", models.IntegerField(blank=True, null=True)),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="population_data.month",
                    ),
                ),
                (
                    "owned_species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="species.ownedspecies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Population counts",
                "db_table": "population_count",
                "unique_together": {("year", "owned_species")},
            },
        ),
    ]
