# Generated by Django 4.1.7 on 2023-06-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("population_data", "0002_populationcountperactivity_populationcount"),
        ("population_data", "0003_rename_owned_populationcount_owned_species_and_more"),
    ]

    dependencies = [
        ("species", "0001_species_models"),
        ("activity", "0001_initial"),
        ("population_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationCount",
            fields=[
                ("year", models.DateField(primary_key=True, serialize=False)),
                ("total", models.IntegerField()),
                ("adult_male", models.IntegerField(blank=True, null=True)),
                ("adult_female", models.IntegerField(blank=True, null=True)),
                ("juvenile_male", models.IntegerField(blank=True, null=True)),
                ("juvenile_female", models.IntegerField(blank=True, null=True)),
                ("sub_adult_total", models.IntegerField(blank=True, null=True)),
                ("sub_adult_male", models.IntegerField(blank=True, null=True)),
                ("sub_adult_female", models.IntegerField(blank=True, null=True)),
                ("juvenile_total", models.IntegerField(blank=True, null=True)),
                ("pride", models.IntegerField(blank=True, null=True)),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="population_data.month",
                    ),
                ),
                ("owned_species", models.ManyToManyField(to="species.ownedspecies")),
            ],
            options={
                "verbose_name": "Population counts",
                "db_table": "population_count",
            },
        ),
        migrations.CreateModel(
            name="PopulationCountPerActivity",
            fields=[
                ("year", models.DateField(primary_key=True, serialize=False)),
                ("total", models.IntegerField()),
                ("adult_male", models.IntegerField(blank=True, null=True)),
                ("adult_female", models.IntegerField(blank=True, null=True)),
                ("juvenile_male", models.IntegerField(blank=True, null=True)),
                ("juvenile_female", models.IntegerField(blank=True, null=True)),
                ("founder_population", models.BooleanField(blank=True, null=True)),
                (
                    "reintroduction_source",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("permit_number", models.IntegerField(blank=True, null=True)),
                ("activity_type", models.ManyToManyField(to="activity.activitytype")),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="population_data.month",
                    ),
                ),
                ("owned_species", models.ManyToManyField(to="species.ownedspecies")),
            ],
            options={
                "verbose_name": "Population count per activities",
                "db_table": "population_count_per_activity",
            },
        ),
    ]
