# Generated by Django 4.1.7 on 2023-06-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("population_data", "0002_populationcountperactivity_populationcount"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="populationcountperactivity",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="populationcount",
            constraint=models.UniqueConstraint(
                fields=("year", "owned_species"), name="unique_population_count"
            ),
        ),
        migrations.AddConstraint(
            model_name="populationcountperactivity",
            constraint=models.UniqueConstraint(
                fields=("year", "owned_species", "activity_type"),
                name="unique_population_count_per_activity",
            ),
        ),
    ]
