# Generated by Django 4.1.7 on 2023-06-12 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "population_data",
            "0003_alter_populationcountperactivity_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="populationcount",
            options={
                "verbose_name": "Population count",
                "verbose_name_plural": "Population counts",
            },
        ),
        migrations.AlterModelOptions(
            name="populationcountperactivity",
            options={
                "verbose_name": "Population count per activity",
                "verbose_name_plural": "Population count per activities",
            },
        ),
        migrations.AlterUniqueTogether(
            name="populationcount",
            unique_together=set(),
        ),
    ]
