# Generated by Django 4.1.7 on 2023-06-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("population_data", "0004_alter_populationcount_options_and_more"),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE population_count ALTER year TYPE INTEGER USING EXTRACT(year FROM year)"),
        migrations.RunSQL("ALTER TABLE population_count_per_activity ALTER year TYPE INTEGER USING EXTRACT(year FROM year)"),
        migrations.AlterField(
            model_name="populationcount",
            name="year",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="populationcountperactivity",
            name="year",
            field=models.PositiveIntegerField(),
        ),
    ]
