# Generated by Django 4.1.7 on 2023-06-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("population_data", "0005_alter_populationcount_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certainty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=250, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description", null=True),
                ),
            ],
            options={
                "verbose_name": "Certainty",
                "verbose_name_plural": "Certainties",
                "db_table": "certainty",
            },
        ),
    ]
