# Generated by Django 4.1.10 on 2023-07-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "population_data",
            "0007_annualpopulation_annualpopulationperactivity_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="annualpopulationperactivity",
            old_name="group",
            new_name="intake_permit",
        ),
        migrations.RenameField(
            model_name="annualpopulationperactivity",
            old_name="permit_number",
            new_name="offtake_permit",
        ),
        migrations.RemoveField(
            model_name="annualpopulationperactivity",
            name="area_covered",
        ),
        migrations.RemoveField(
            model_name="annualpopulationperactivity",
            name="certainty",
        ),
        migrations.RemoveField(
            model_name="annualpopulationperactivity",
            name="count_method",
        ),
        migrations.RemoveField(
            model_name="annualpopulationperactivity",
            name="open_close_system",
        ),
        migrations.RemoveField(
            model_name="annualpopulationperactivity",
            name="sampling_effort",
        ),
        migrations.RemoveField(
            model_name="annualpopulationperactivity",
            name="sampling_size_unit",
        ),
        migrations.RemoveField(
            model_name="annualpopulationperactivity",
            name="survey_method",
        ),
        migrations.AddField(
            model_name="annualpopulation",
            name="presence",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="annualpopulationperactivity",
            name="translocation_destination",
            field=models.TextField(blank=True, null=True),
        ),
    ]
