# Generated by Django 4.1.10 on 2023-07-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'population_data',
            '0007_annualpopulation_annualpopulationperactivity_and_more',
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='annualpopulation',
            name='unique_population_count',
        ),
        migrations.AddConstraint(
            model_name='annualpopulation',
            constraint=models.UniqueConstraint(
                fields=('year', 'owned_species', 'month'),
                name='unique_population_count',
            ),
        ),
    ]
