# Generated by Django 4.1.10 on 2023-07-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "population_data",
            "0008_rename_group_annualpopulationperactivity_intake_permit_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="annualpopulation",
            name="unique_population_count",
        ),
        migrations.AddConstraint(
            model_name="annualpopulation",
            constraint=models.UniqueConstraint(
                fields=("year", "owned_species", "month"),
                name="unique_population_count",
            ),
        ),
    ]
