# Generated by Django 4.1.10 on 2023-07-21 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "population_data",
            "0008_remove_annualpopulation_unique_population_count_and_more",
        ),
        (
            "population_data",
            "0008_rename_group_annualpopulationperactivity_intake_permit_and_more",
        ),
    ]

    operations = []
