# Generated by Django 4.1.10 on 2023-08-21 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "population_data",
            "0010_populationestimatecategory_populationstatus_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SamplingEffortCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="", help_text="Name", unique=True)),
            ],
            options={
                "verbose_name": "Sampling Effort Coverage",
                "verbose_name_plural": "Sampling Effort Coverages",
                "db_table": "sampling_effort_coverage",
            },
        ),
        migrations.RemoveConstraint(
            model_name="annualpopulationperactivity",
            name="unique_population_count_per_activity",
        ),
        migrations.RemoveField(
            model_name="annualpopulation",
            name="area_covered",
        ),
        migrations.RemoveField(
            model_name="annualpopulation",
            name="sampling_effort",
        ),
        migrations.AddField(
            model_name="annualpopulation",
            name="certainty_of_bounds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annualpopulation",
            name="lower_confidence_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annualpopulation",
            name="population_estimate_certainty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annualpopulation",
            name="upper_confidence_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annualpopulationperactivity",
            name="intake_permit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="annualpopulationperactivity",
            name="offtake_permit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="annualpopulationperactivity",
            constraint=models.UniqueConstraint(
                fields=(
                    "year",
                    "owned_species",
                    "activity_type",
                    "intake_permit",
                    "offtake_permit",
                ),
                name="unique_population_count_per_activity",
            ),
        ),
        migrations.AddField(
            model_name="annualpopulation",
            name="sampling_effort_coverage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="population_data.samplingeffortcoverage",
            ),
        ),
    ]
