# Generated by Django 4.1.10 on 2023-09-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "population_data",
            "0012_remove_annualpopulationperactivity_unique_population_count_per_activity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="annualpopulation",
            name="population_estimate_category_other",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annualpopulation",
            name="survey_method_other",
            field=models.TextField(blank=True, null=True),
        ),
    ]
