# Generated by Django 4.1.10 on 2023-09-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "population_data",
            "0013_annualpopulation_population_estimate_category_other_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certainty",
            options={
                "verbose_name": "Population estimate certainty",
                "verbose_name_plural": "Population estimate certainties",
            },
        ),
        migrations.RemoveField(
            model_name="annualpopulation",
            name="count_method",
        ),
        migrations.AddField(
            model_name="samplingeffortcoverage",
            name="sort_order",
            field=models.IntegerField(
                help_text="Order sampling effort coverage model.",
                null=True,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="CountMethod",
        ),
    ]
