# Generated by Django 4.1.10 on 2023-09-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("population_data", "0014_alter_certainty_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualpopulation",
            name="population_estimate_certainty",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                null=True,
            ),
        ),
    ]
