# Generated by Django 4.1.10 on 2023-10-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "population_data",
            "0015_alter_annualpopulation_population_estimate_certainty",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="annualpopulation",
            index=models.Index(
                fields=["owned_species_id", "year"],
                name="annual_popu_owned_s_b60c39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annualpopulationperactivity",
            index=models.Index(
                fields=["owned_species_id", "year"],
                name="annual_popu_owned_s_a8b96e_idx",
            ),
        ),
    ]
