# Generated by Django 4.1.10 on 2023-10-26 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0009_taxon_graph_icon"),
        (
            "population_data",
            "0016_remove_annualpopulationperactivity_unique_population_count_per_activity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualpopulation",
            name="owned_species",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="species.ownedspecies",
            ),
        ),
        migrations.AlterField(
            model_name="annualpopulationperactivity",
            name="owned_species",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="species.ownedspecies",
            ),
        ),
    ]
