# Generated by Django 4.1.10 on 2023-10-30 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("population_data", "0017_alter_annualpopulation_owned_species_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualpopulation",
            name="owned_species",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="species.ownedspecies",
            ),
        ),
        migrations.AlterField(
            model_name="annualpopulationperactivity",
            name="owned_species",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="species.ownedspecies",
            ),
        ),
    ]
