# Generated by Django 4.1.10 on 2023-11-06 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("population_data", "0018_auto_20231030_0220"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="annualpopulation",
            name="Adult male and adult female must not be greater than total",
        ),
    ]
