# Generated by Django 4.1.13 on 2023-11-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "population_data",
            "0019_remove_annualpopulation_adult male and adult female must not be greater than total",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="annualpopulation",
            name="adult_total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
