# Generated by Django 4.1.13 on 2023-12-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("population_data", "0020_annualpopulation_adult_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualpopulation",
            name="population_estimate_category_other",
            field=models.TextField(
                blank=True,
                help_text="If population estimate category is other, then please explain",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="annualpopulation",
            name="survey_method_other",
            field=models.TextField(
                blank=True,
                help_text="If survey method is other, then please explain",
                null=True,
            ),
        ),
    ]
