# Generated by Django 4.1.13 on 2024-02-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "population_data",
            "0021_alter_annualpopulation_population_estimate_category_other_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annualpopulation",
            name="owned_species",
        ),
        migrations.RemoveField(
            model_name="annualpopulationperactivity",
            name="owned_species",
        ),
    ]
