# Generated by Django 4.1.13 on 2024-07-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("population_data", "0022_remove_annualpopulation_owned_species_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualpopulationperactivity",
            name="total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
