version: '3.9'
services:
  db:
    volumes:
      - ./volumes/database:/opt/postgres/data
      - ./volumes/backups:/backups
    ports:
      - "${DATABASE_PORT:-6432}:5432"

  dbbackups:
    volumes:
      - ./volumes/backups:/backups

  django:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: prod
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media

  worker:
    image: kartoza/sanbi_dev
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/media:/home/web/media
      - ./volumes/layer_tiles:/opt/layer_tiles

  dev:
    build:
      context: ../
      dockerfile: deployment/docker/Dockerfile
      target: dev
    volumes:
      - ../django_project:/home/web/django_project
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
    ports:
      # for django test server
      - "${DEV_SERVER:-61100}:8080"
      # for django frontend server
      - "${FRONTEND_SERVER:-9000}:9000"
      # for ssh
      - "${SSH_PORT:-61102}:22"

  tegola:
    volumes:
      - ./tegola:/opt/tegola_config
      - ./volumes/layer_tiles:/opt/layer_tiles

  nginx:
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ./volumes/static:/home/web/static
      - ./volumes/media:/home/web/media
      - ./volumes/layer_tiles:/home/web/layer_tiles
    ports:
      - "${HTTP_PORT:-8888}:80"
    links:
      - django
      - tegola
