version: '3.9'

volumes:
  static-data:
  media-data:
  conf-data:
  database:
  nginx-cache:
  backups-data:
  data-volume:
  layer-tiles:
  plumber-data:

x-tegola-image: &tegola-image gospatial/tegola:v0.16.0
x-common-django:
  &default-common-django
  image: kartoza/${COMPOSE_PROJECT_NAME:-django_project}:${DJANGO_TAG:-0.0.1}
  environment:
    # editable in .env
    - DATABASE_NAME=${DATABASE_NAME:-django}
    - DATABASE_USERNAME=${DATABASE_USERNAME:-docker}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD:-docker}
    - DATABASE_HOST=${DATABASE_HOST:-db}
    - REDIS_HOST=${REDIS_HOST:-redis}
    - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
    - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
    - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-core.settings.prod}
    - INITIAL_FIXTURES=${INITIAL_FIXTURES:-False}
    - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-[]}
    - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-production}
    - SENTRY_DSN=${SENTRY_DSN}
    - MAPTILER_API_KEY=${MAPTILER_API_KEY:-''}

    # Email where alters should be sent. This will be used by let's encrypt and as the django admin email.
    - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
    - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
  volumes:
    - static-data:/home/web/static
    - media-data:/home/web/media
    - plumber-data:/home/web/plumber_data
  restart: on-failure

services:
  redis:
    image: bitnami/redis:7.0.2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}

  db:
    image: kartoza/postgis:14-3.3
    shm_size: 1g
    volumes:
      - data-volume:/opt/postgres/data
    environment:
      - DATADIR=/opt/postgres/data
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_DBNAME=${DATABASE_NAME:-django}
      - POSTGRES_USER=${DATABASE_USERNAME:-docker}
      - POSTGRES_PASS=${DATABASE_PASSWORD:-docker}

  dbbackups:
    image: kartoza/pg-backup:14-3.3
    environment:
      # take care to let the project name below match that
      # declared in the top of the makefile
      - DUMPPREFIX=PG_Sanbi
      # These are all defaults anyway, but setting explicitly in
      # case we ever want to ever use different credentials
      - POSTGRES_USER=${DATABASE_USERNAME:-docker}
      - POSTGRES_PASS=${DATABASE_PASSWORD:-docker}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
      - POSTGRES_DBNAME=${DATABASE_NAME:-django}
      - DBLIST=django
    volumes:
      - backups-data:/backups
    restart: on-failure:5

  django:
    <<: *default-common-django
    command: 'uwsgi --ini /uwsgi.conf'
    links:
      - db
      - worker
      - plumber

  worker:
    <<: *default-common-django
    entrypoint: []
    command: 'celery -A core worker -l info'
    volumes:
      - layer-tiles:/opt/layer_tiles
    links:
      - db
      - redis

  beat:  # Define the Celery beat service
    <<: *default-common-django
    entrypoint: []
    command: 'celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler'
    volumes:
      - layer-tiles:/opt/layer_tiles
    links:
      - redis

  dev:
    image: kartoza/sanbi_dev
    <<: *default-common-django
    entrypoint: []
    links:
      - db
      - worker
      - plumber

  tegola:
    image: *tegola-image
    entrypoint: /opt/tegola
    command: serve --config /opt/tegola_config/tegola.conf
    volumes:
      - layer-tiles:/opt/layer_tiles
    links:
      - db
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-docker}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-docker}
      - POSTGRES_DBNAME=${DATABASE_NAME:-django}
      - POSTGRES_HOST=${DATABASE_HOST:-db}
      - POSTGRES_PRIVATE_PORT=5432
      - SSL_MODE=prefer
      - TEGOLA_PORT=9090
      - TEGOLA_SQL_DEBUG=EXECUTE_SQL #LAYER_SQL  or EXECUTE_SQL
    restart: on-failure

  nginx:
    image: nginx
    hostname: nginx
    volumes:
      - conf-data:/etc/nginx/conf.d:ro
      - static-data:/home/web/static
      - media-data:/home/web/media
      - nginx-cache:/home/web/nginx_cache
      - layer-tiles:/home/web/layer_tiles
    links:
      - django
      - tegola

  plumber:
    build:
      context: ../
      dockerfile: deployment/plumber/Dockerfile
    environment:
      # editable in .env
      - DATABASE_NAME=${DATABASE_NAME:-django}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-docker}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-docker}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-core.settings.prod}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-production}
      - SENTRY_DSN=${SENTRY_DSN}
      - PLUMBER_PORT=${PLUMBER_PORT:-8181}
    volumes:
      - plumber-data:/home/web/plumber_data
      - media-data:/home/web/media
    links:
      - db
      - redis
