# Generated by Django 4.1.10 on 2023-10-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytype",
            name="colour",
            field=models.CharField(default="#000000", max_length=20),
        ),
        migrations.AddField(
            model_name="activitytype",
            name="export_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Fields that will be taken from Annual Population Per Activity table when exporting Activity Report. Input as Array e.g. ["intake_permit", "translocation_destination"]',
            ),
        ),
        migrations.AddField(
            model_name="activitytype",
            name="width",
            field=models.FloatField(
                default=130.2,
                help_text="Column width in the Activity Report. The default is 130.2.",
            ),
        ),
    ]
