# Generated by Django 4.1.10 on 2023-10-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytype",
            name="colour",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="activitytype",
            name="export_fields",
            field=models.JSONField(
                default=list,
                help_text='Fields that will be taken from Annual Population Per Activity table when exporting Activity Report. Input as Array e.g. ["intake_permit", "translocation_destination"]',
            ),
        ),
    ]
