# Generated by Django 4.1.7 on 2023-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TaxonRank',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Taxon Rank',
                'verbose_name_plural': 'Taxon Ranks',
                'db_table': 'taxon_rank',
            },
        ),
    ]