# Generated by Django 4.1.7 on 2023-06-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManagementStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Management Status",
                "verbose_name_plural": "Management Status",
                "db_table": "management_status",
            },
        ),
        migrations.CreateModel(
            name="TaxonRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name": "Taxon Rank",
                "verbose_name_plural": "Taxon Ranks",
                "db_table": "taxon_rank",
            },
        ),
        migrations.CreateModel(
            name="Taxon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scientific_name", models.CharField(max_length=250, unique=True)),
                (
                    "common_name_varbatim",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("colour_variant", models.BooleanField()),
                (
                    "infraspecific_epithet",
                    models.CharField(
                        blank=True, max_length=250, null=True, unique=True
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="species.taxon",
                    ),
                ),
                (
                    "taxon_rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="species.taxonrank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxon",
                "verbose_name_plural": "Taxa",
                "db_table": "taxon",
            },
        ),
    ]
