# Generated by Django 4.1.7 on 2023-06-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManagementStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Management Status",
                "verbose_name_plural": "Management Status",
                "db_table": "management_status",
            },
        ),
        migrations.CreateModel(
            name="TaxonRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name": "Taxon Rank",
                "verbose_name_plural": "Taxon Ranks",
                "db_table": "taxon_rank",
            },
        ),
    ]
