# Generated by Django 4.1.7 on 2023-06-10 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [("species", "0001_initial"), ("species", "0002_ownedspecies")]

    initial = True

    dependencies = [
        ("property", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("population_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Management Status",
                "verbose_name_plural": "Management Status",
                "db_table": "management_status",
            },
        ),
        migrations.CreateModel(
            name="TaxonRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name": "Taxon Rank",
                "verbose_name_plural": "Taxon Ranks",
                "db_table": "taxon_rank",
            },
        ),
        migrations.CreateModel(
            name="Taxon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scientific_name", models.CharField(max_length=250, unique=True)),
                (
                    "common_name_varbatim",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("colour_variant", models.BooleanField()),
                (
                    "infraspecific_epithet",
                    models.CharField(
                        blank=True, max_length=250, null=True, unique=True
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="species.taxon",
                    ),
                ),
                (
                    "taxon_rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="species.taxonrank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxon",
                "verbose_name_plural": "Taxa",
                "db_table": "taxon",
            },
        ),
        migrations.CreateModel(
            name="OwnedSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="population_data.countmethod",
                    ),
                ),
                (
                    "management_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="species.managementstatus",
                    ),
                ),
                (
                    "nature_of_population",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="population_data.natureofpopulation",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="property.property",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="species.taxon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Owned Species",
                "verbose_name_plural": "Owned Species",
                "db_table": "owned_species",
            },
        ),
    ]
