# Generated by Django 4.1.7 on 2023-06-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0001_taxon_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scientific_name", models.CharField(max_length=250, unique=True)),
                (
                    "common_name_varbatim",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("colour_variant", models.BooleanField()),
                (
                    "infraspecific_epithet",
                    models.CharField(
                        blank=True, max_length=250, null=True, unique=True
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="species.taxon",
                    ),
                ),
                (
                    "taxon_rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="species.taxonrank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxon",
                "verbose_name_plural": "Taxa",
                "db_table": "taxon",
            },
        ),
    ]
