# Generated by Django 4.1.7 on 2023-06-29 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("occurrence", "0002_alter_occurrence_basis_of_record_and_more"),
        ("species", "0002_alter_ownedspecies_count_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxonSurveyMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="occurrence.surveymethod",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="species.taxon"
                    ),
                ),
            ],
        ),
    ]
