# Generated by Django 4.1.7 on 2023-06-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0003_taxonsurveymethod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ownedspecies",
            name="count_method",
        ),
        migrations.AddField(
            model_name="ownedspecies",
            name="area_available_to_species",
            field=models.FloatField(default=0.0),
        ),
    ]
