# Generated by Django 4.1.7 on 2023-07-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0004_remove_ownedspecies_count_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="colour",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="taxon",
            name="front_page_order",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Front page order"
            ),
        ),
        migrations.AddField(
            model_name="taxon",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taxon",
            name="show_on_front_page",
            field=models.BooleanField(default=False),
        ),
    ]
