# Generated by Django 4.1.10 on 2023-08-01 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0006_taxon_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ownedspecies",
            name="management_status",
        ),
        migrations.RemoveField(
            model_name="ownedspecies",
            name="nature_of_population",
        ),
        migrations.DeleteModel(
            name="ManagementStatus",
        ),
    ]
