# Generated by Django 4.1.10 on 2023-08-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0008_alter_taxon_colour_variant_alter_taxon_taxon_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="graph_icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="taxon_graph_icons"
            ),
        ),
    ]
