# Generated by Django 4.1.10 on 2023-11-03 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0009_taxon_graph_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxon",
            name="topper_icon",
            field=models.FileField(
                blank=True,
                help_text="Will be generated automatically from graph_icon to be used in Report and Charts topper. Please re-upload graph_icon to regenerate topper_icon.",
                null=True,
                upload_to="taxon_topper_icons",
                validators=[django.core.validators.FileExtensionValidator(["svg"])],
            ),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="graph_icon",
            field=models.FileField(
                blank=True,
                help_text="Use SVG file with black (#000000) fill and transparent background. It will be used as species icon in graph/charts.",
                null=True,
                upload_to="taxon_graph_icons",
                validators=[django.core.validators.FileExtensionValidator(["svg"])],
            ),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="icon",
            field=models.FileField(
                blank=True,
                help_text="Will be generated automatically from graph_icon to be used in population overview. Please re-upload graph_icon to regenerate icon.",
                null=True,
                upload_to="taxon_icons",
            ),
        ),
    ]
