# Generated by Django 4.1.13 on 2023-11-20 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0010_taxon_topper_icon_alter_taxon_graph_icon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taxon",
            old_name="common_name_varbatim",
            new_name="common_name_verbatim",
        ),
    ]
