# Generated by Django 4.1.13 on 2024-03-04 05:49

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    if 'easyaudit' in settings.INSTALLED_APPS:
        dependencies = [
            ("easyaudit", "__latest__"),
        ]
    else:
        dependencies = []

    operations = [
        migrations.CreateModel(
            name="SitePreferences",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_title", models.CharField(default="SANBI", max_length=512)),
                (
                    "property_overlaps_threshold",
                    models.FloatField(
                        blank=True,
                        default=1,
                        help_text="Threshold for checking overlaps between properties (in sqm).",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
