# Generated by Django 4.1.13 on 2024-03-04 05:52

from django.db import migrations


def add_site_preferences(apps, schema_editor):
    SitePreferences = apps.get_model('core', 'SitePreferences')
    if not SitePreferences.objects.exists():
        SitePreferences.objects.create(
            site_title='SANBI'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_site_preferences)
    ]
