# Generated by Django 4.1.7 on 2023-06-13 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0003_add_parcel_label_tables"),
        ("frontend", "0003_tile_bbox"),
    ]

    operations = []
