# Generated by Django 4.1.7 on 2023-06-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0004_merge_0003_add_parcel_label_tables_0003_tile_bbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erf",
            name="cname",
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="farmportion",
            name="cname",
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="holding",
            name="cname",
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="parentfarm",
            name="cname",
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
    ]
