# Generated by Django 4.1.7 on 2023-06-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0004_merge_0003_add_parcel_label_tables_0003_tile_bbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContextLayerTilingTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("PR", "Processing"),
                            ("DO", "Done"),
                            ("ER", "Error"),
                            ("CD", "Cancelled"),
                        ],
                        default="PE",
                        max_length=2,
                    ),
                ),
                ("task_id", models.CharField(blank=True, null=True, default="", max_length=256)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("total_size", models.TextField(blank=True, default="", null=True)),
                ("task_return_code", models.IntegerField(blank=True, null=True)),
                ("log", models.TextField(blank=True, null=True, default="")),
                ("error_log", models.TextField(blank=True, null=True, default="")),
                ("config_path", models.TextField(blank=True, null=True, default="")),
            ],
        ),
    ]
