# Generated by Django 4.1.7 on 2023-06-20 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("frontend", "0005_alter_erf_cname_alter_farmportion_cname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoundaryFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(max_length=256)),
                ("meta_id", models.CharField(blank=True, default="", max_length=256)),
                ("upload_date", models.DateTimeField(blank=True, null=True)),
                ("file", models.FileField(upload_to="boundary_files/%Y/%m/%d/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("GEOJSON", "GEOJSON"),
                            ("SHAPEFILE", "SHAPEFILE"),
                            ("GEOPACKAGE", "GEOPACKAGE"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=512)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
