# Generated by Django 4.1.7 on 2023-06-19 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0005_alter_erf_cname_alter_farmportion_cname_and_more"),
        ("frontend", "0005_contextlayertilingtask"),
    ]

    operations = []
