# Generated by Django 4.1.7 on 2023-06-21 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0005_alter_erf_cname_alter_farmportion_cname_and_more"),
    ]

    # altering world geometry to make SADC countries line up
    operations = [
        migrations.RunSQL(
            """alter table layer.world
            alter column geom
            Type Geometry(multipolygon, 3857)
            using ST_transform(geom, 3857)""",
            reverse_sql=(
                """alter table layer.world
                alter column geom
                Type Geometry(multipolygon, 4326)
                using ST_transform(geom, 4326)"""
            ),
            elidable=False
        )
    ]
