# Generated by Django 4.1.7 on 2023-06-21 11:36

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("frontend", "0007_style_v9"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoundarySearchRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("DONE", "DONE"),
                            ("ERROR", "ERROR"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, max_length=256, null=True)),
                ("progress", models.FloatField(blank=True, null=True)),
                ("progress_text", models.TextField(blank=True, null=True)),
                ("type", models.CharField(help_text="File/Digitise", max_length=256)),
                ("session", models.CharField(max_length=256)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("parcels", models.JSONField(blank=True, default=[], null=True)),
                (
                    "request_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(max_length=256)),
                ("meta_id", models.CharField(blank=True, default="", max_length=256)),
                ("upload_date", models.DateTimeField(blank=True, null=True)),
                ("file", models.FileField(upload_to="boundary_files/%Y/%m/%d/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("GEOJSON", "GEOJSON"),
                            ("SHAPEFILE", "SHAPEFILE"),
                            ("GEOPACKAGE", "GEOPACKAGE"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=512)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
