# Generated by Django 4.1.7 on 2023-07-07 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0005_taxon_colour_taxon_front_page_order_and_more"),
        ("property", "0004_remove_property_ownership_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("frontend", "0009_contextlayerlegend"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftSpeciesUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("upload_date", models.DateTimeField()),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("last_step", models.PositiveIntegerField(blank=True, null=True)),
                ("form_data", models.JSONField(blank=True, default={}, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.property",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="species.taxon",
                    ),
                ),
                (
                    "upload_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
