# Generated by Django 4.1.7 on 2023-07-10 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0010_draftspeciesupload"),
        ("frontend", "0010_layer_simplification"),
    ]

    operations = []
