# Generated by Django 4.1.10 on 2023-07-19 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0005_taxon_colour_taxon_front_page_order_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("frontend", "0011_merge_20230710_0834"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticalModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("code", models.TextField(blank=True, null=True)),
                ("is_valid", models.BooleanField(null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                (
                    "taxon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="species.taxon"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatisticalTaskRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("DONE", "DONE"),
                            ("ERROR", "ERROR"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, max_length=256, null=True)),
                ("progress", models.FloatField(blank=True, null=True)),
                ("progress_text", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="statistical/%Y/%m/%d/"
                    ),
                ),
                ("response", models.JSONField(blank=True, default=dict, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("is_success", models.BooleanField(null=True)),
                ("return_code", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "request_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "statistical_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.statisticalmodel",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="species.taxon"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
