# Generated by Django 4.1.10 on 2023-08-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0013_alter_statisticalmodel_taxon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statisticalmodeloutput",
            name="type",
            field=models.CharField(
                choices=[
                    ("national_trend", "National Trend"),
                    ("population_per_province", "Population Per Province"),
                    ("province_trend", "Province Trend"),
                    ("property_trend", "Property Trend"),
                ],
                max_length=100,
            ),
        ),
    ]
