# Generated by Django 4.1.10 on 2023-09-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0014_uploadspeciescsv"),
    ]

    operations = [
        migrations.AddField(
            model_name="boundarysearchrequest",
            name="used_parcels",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="boundarysearchrequest",
            name="parcels",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
