# Generated by Django 4.1.10 on 2023-09-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0005_remove_property_area_available_property_open"),
        ("frontend", "0014_uploadspeciescsv"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpatialDataModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="frontend.contextlayer",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spatial data",
                "verbose_name_plural": "Spatial data",
            },
        ),
        migrations.CreateModel(
            name="SpatialDataValueModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_layer_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spatial_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="frontend.spatialdatamodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spatial data value",
                "verbose_name_plural": "Spatial data values",
            },
        ),
    ]
