# Generated by Django 4.1.10 on 2023-09-11 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0015_add_province_labels_table"),
        ("frontend", "0015_spatialdatamodel_spatialdatavaluemodel"),
    ]

    operations = []
