# Generated by Django 4.1.10 on 2023-09-18 23:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0018_alter_boundaryfile_file_type"),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE TABLE IF NOT EXISTS layer.place_name_larger_scale (
                id int8 NULL,
                geom public.geometry(point, 3857) NULL,
                fclass varchar(28) NULL,
                name varchar(100) NULL
            );""",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """CREATE TABLE IF NOT EXISTS layer.place_name_largest_scale (
                id int8 NULL,
                geom public.geometry(point, 3857) NULL,
                fclass varchar(28) NULL,
                name varchar(100) NULL
            );""",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """CREATE TABLE IF NOT EXISTS layer.place_name_midscale (
                id int8 NULL,
                geom public.geometry(point, 3857) NULL,
                fclass varchar(28) NULL,
                name varchar(100) NULL
            );""",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """CREATE TABLE IF NOT EXISTS layer.place_name_smallest_scale (
                id int8 NULL,
                geom public.geometry(point, 3857) NULL,
                fclass varchar(28) NULL,
                name varchar(100) NULL
            );""",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.CreateModel(
            name="PlaceNameLargerScale",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=3857
                    ),
                ),
                ("fclass", models.CharField(blank=True, max_length=28, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": 'layer"."place_name_larger_scale',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlaceNameLargestScale",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=3857
                    ),
                ),
                ("fclass", models.CharField(blank=True, max_length=28, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": 'layer"."place_name_largest_scale',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlaceNameMidScale",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=3857
                    ),
                ),
                ("fclass", models.CharField(blank=True, max_length=28, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": 'layer"."place_name_midscale',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlaceNameSmallScale",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=3857
                    ),
                ),
                ("fclass", models.CharField(blank=True, max_length=28, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": 'layer"."place_name_smallest_scale',
                "managed": False,
            },
        ),
        migrations.RunSQL(
            """CREATE index if not exists place_name_larger_scale_name_idx ON layer.place_name_larger_scale (name);
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """CREATE index if not exists place_name_largest_scale_name_idx ON layer.place_name_largest_scale (name);
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """CREATE index if not exists place_name_midscale_name_idx ON layer.place_name_midscale (name);
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """CREATE index if not exists place_name_small_scale_name_idx ON layer.place_name_smallest_scale (name);
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
