# Generated by Django 4.1.10 on 2023-09-18 04:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0018_alter_boundaryfile_file_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Road",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=3857
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, max_length=80, null=True
                    ),
                ),
                ("highway", models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                "db_table": 'layer"."zaf_roads',
                "managed": False,
            },
        ),
        migrations.RunSQL(
            """CREATE index if not exists zaf_roads_name_idx ON layer.zaf_roads (name);
            """,
            reverse_sql=migrations.RunSQL.noop
        )
    ]
