# Generated by Django 4.1.10 on 2023-10-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0019_placenamelargerscale_placenamelargestscale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contextlayer",
            name="layer_names",
            field=models.JSONField(
                blank=True,
                default=[],
                help_text='A list of names for different layers. E.g ["layer_1", "layer_2"].',
            ),
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='The unique name that identifies this layer. E.g., "Roads", "Buildings", etc.',
                        max_length=512,
                    ),
                ),
                (
                    "spatial_filter_field",
                    models.TextField(
                        blank=True,
                        help_text='The specific field within this layer used for spatial filtering. For instance, if filtering by region, this could be a field like "region_name".',
                        null=True,
                    ),
                ),
                (
                    "context_layer",
                    models.ForeignKey(
                        help_text="The context layer to which this individual layer belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.contextlayer",
                    ),
                ),
            ],
        ),
    ]
