# Generated by Django 4.1.10 on 2023-10-01 07:01

from django.db import migrations

def create_layers_from_context_layer(apps, schema_editor):
    ContextLayer = apps.get_model('frontend', 'ContextLayer')
    Layer = apps.get_model('frontend', 'Layer')

    for context_layer in ContextLayer.objects.all():
        for layer_name in context_layer.layer_names:
            Layer.objects.create(name=layer_name, context_layer=context_layer)


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0020_alter_contextlayer_layer_names_layer"),
    ]

    operations = [
        migrations.RunPython(create_layers_from_context_layer)
    ]
