# Generated by Django 4.1.10 on 2023-10-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0021_auto_20231001_0701"),
    ]

    operations = [
        migrations.AddField(
            model_name="spatialdatavaluemodel",
            name="layer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.layer",
            ),
        ),
        migrations.AlterField(
            model_name="spatialdatavaluemodel",
            name="spatial_data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.spatialdatamodel",
            ),
        ),
    ]
