# Generated by Django 4.1.10 on 2023-10-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0022_spatialdatavaluemodel_layer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layer",
            options={"ordering": ["display_order"]},
        ),
        migrations.AddField(
            model_name="layer",
            name="display_order",
            field=models.IntegerField(
                default=0, help_text="Order in which the layer should be displayed."
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="is_filter_layer",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this layer is used as a spatial filter.",
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="layer_title",
            field=models.CharField(
                blank=True, default="", help_text="Title of the layer.", max_length=512
            ),
        ),
    ]
