# Generated by Django 4.1.10 on 2023-10-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0023_alter_layer_options_layer_display_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statisticalmodeloutput",
            name="type",
            field=models.CharField(
                choices=[
                    ("national_trend", "National Trend"),
                    ("population_per_province", "Population Per Province"),
                    ("province_trend", "Province Trend"),
                    ("property_trend", "Property Trend"),
                    ("population_per_property", "Population Per Property"),
                    ("species_per_property", "Species Per Property"),
                ],
                max_length=100,
            ),
        ),
    ]
