# Generated by Django 4.1.10 on 2023-10-13 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0024_alter_statisticalmodeloutput_type"),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE TABLE IF NOT EXISTS layer.zaf_provinces_small_scale (
                id int8 NULL,
                geom public.geometry NULL,
                adm1_en varchar(50) NULL
            );""",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            """CREATE UNIQUE INDEX IF NOT EXISTS zaf_provinces_small_scale_adm1_en_idx ON
                layer.zaf_provinces_small_scale
                USING btree (adm1_en);
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
