# Generated by Django 4.1.10 on 2023-10-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0025_add_idx_province_layer"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="spatialdatavaluemodel",
            index=models.Index(
                fields=["spatial_data_id", "context_layer_value"],
                name="frontend_sp_spatial_50ad24_idx",
            ),
        ),
    ]
