# Generated by Django 4.1.13 on 2023-11-15 22:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0010_taxon_topper_icon_alter_taxon_graph_icon_and_more"),
        ("frontend", "0028_alter_spatialdatamodel_context_layer"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticalmodeloutput",
            name="variable_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="statisticalmodeloutput",
            name="type",
            field=models.CharField(
                choices=[
                    ("national_trend", "National Trend"),
                    ("province_trend", "Province Trend"),
                    ("property_trend", "Property Trend"),
                    ("species_per_property", "Species Per Property"),
                    ("national_growth", "National Growth"),
                    ("provincial_growth", "Provincial Growth"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="SpeciesModelOutput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("DONE", "DONE"),
                            ("ERROR", "ERROR"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, max_length=256, null=True)),
                ("progress", models.FloatField(blank=True, null=True)),
                ("progress_text", models.TextField(blank=True, null=True)),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="statistical/%Y/%m/%d/"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("is_latest", models.BooleanField(default=False)),
                ("generated_on", models.DateTimeField(blank=True, null=True)),
                ("is_outdated", models.BooleanField(default=False)),
                ("outdated_since", models.DateTimeField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.statisticalmodel",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="species.taxon"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
