# Generated by Django 4.1.13 on 2023-11-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0029_statisticalmodeloutput_variable_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statisticalmodeloutput",
            name="type",
            field=models.CharField(
                choices=[
                    ("national_trend", "National Trend"),
                    ("province_trend", "Province Trend"),
                    ("property_trend", "Property Trend"),
                    ("species_per_property", "Species Per Property"),
                    ("national_growth", "National Growth"),
                    ("provincial_growth", "Provincial Growth"),
                    ("other_data", "Other Data"),
                ],
                max_length=100,
            ),
        ),
    ]
