# Generated by Django 4.1.13 on 2023-11-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0030_alter_statisticalmodeloutput_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciesmodeloutput",
            name="input_file",
            field=models.FileField(
                blank=True, null=True, upload_to="statistical/input/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="speciesmodeloutput",
            name="output_file",
            field=models.FileField(
                blank=True, null=True, upload_to="statistical/output/%Y/%m/%d/"
            ),
        ),
    ]
