# Generated by Django 4.1.13 on 2023-11-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0031_speciesmodeloutput_input_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boundarysearchrequest",
            name="errors",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="speciesmodeloutput",
            name="errors",
            field=models.TextField(blank=True, null=True),
        ),
    ]
