# Generated by Django 4.1.10 on 2024-04-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0032_boundarysearchrequest_errors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spreadsheet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "spreadsheet_file",
                    models.FileField(
                        max_length=512, null=True, upload_to="spreadsheet"
                    ),
                ),
            ],
        ),
    ]
