# Generated by Django 4.1.13 on 2024-02-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0033_boundarysearchrequest_property_size_ha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contextlayer",
            name="description",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
