# Generated by Django 4.1.13 on 2024-04-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0034_contextlayer_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutputTypeCategoryIndex",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="The attribute name with/without the type name. e.g. pop_change_cat or national_growth__pop_change_cat",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Part of category value. e.g. steady decrease",
                        max_length=255,
                    ),
                ),
                ("sort_index", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="statisticalmodeloutput",
            name="type",
            field=models.CharField(
                choices=[
                    ("national_trend", "National Trend"),
                    ("province_trend", "Province Trend"),
                    ("property_trend", "Property Trend"),
                    ("species_per_property", "Species Per Property"),
                    ("national_growth", "National Growth"),
                    ("provincial_growth", "Provincial Growth"),
                    ("national_growth_category", "National Growth Category"),
                    ("other_data", "Other Data"),
                ],
                max_length=100,
            ),
        ),
    ]
