# Generated by Django 4.1.13 on 2024-06-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0035_outputtypecategoryindex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statisticalmodeloutput",
            name="type",
            field=models.CharField(
                choices=[
                    ("national_trend", "National Trend"),
                    ("province_trend", "Province Trend"),
                    ("property_trend", "Property Trend"),
                    ("species_per_property", "Species Per Property"),
                    ("national_growth", "National Growth"),
                    ("provincial_growth", "Provincial Growth"),
                    ("national_growth_category", "National Growth Category"),
                    (
                        "num_properties_per_pop_size_cat",
                        "Number of Properties Per Population Size Category",
                    ),
                    (
                        "num_properties_per_density_cat",
                        "Number of Properties Per Density Category",
                    ),
                    ("other_data", "Other Data"),
                ],
                max_length=100,
            ),
        ),
    ]
