# Generated by Django 4.1.7 on 2023-06-11 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_property_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="parcel_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="property.parceltype"
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="property.property"
            ),
        ),
    ]
