# Generated by Django 4.1.7 on 2023-06-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParcelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Parcel type",
                "verbose_name_plural": "Parcel types",
                "db_table": "parcel_type",
            },
        ),
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sg_number", models.CharField(max_length=100, unique=True)),
                ("year", models.DateField()),
                (
                    "parcel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="property.parceltype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcel",
                "verbose_name_plural": "Parcels",
                "db_table": "parcel",
            },
        ),
    ]
