# Generated by Django 4.1.7 on 2023-06-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnershipStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "ownership status",
                "verbose_name_plural": "ownership status",
                "db_table": "ownership_status",
            },
        ),
    ]
