# Generated by Django 4.1.10 on 2023-08-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0004_remove_property_ownership_status_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="property",
            name="check property size",
        ),
        migrations.RemoveField(
            model_name="property",
            name="area_available",
        ),
        migrations.AddField(
            model_name="property",
            name="open",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
