# Generated by Django 4.1.10 on 2023-08-02 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0005_remove_property_area_available_property_open"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="property",
            name="check property size",
        ),
    ]
