# Generated by Django 4.1.10 on 2023-10-17 12:42

from django.db import migrations, models
from property.tasks import update_organisation_property_short_code


def create_short_code(apps, schema_editor):
    Province = apps.get_model('property', 'Province')
    Property = apps.get_model('property', 'Property')

    for province in Province.objects.all():
        update_organisation_property_short_code(
            province_id=province.id,
            update_organisation=False,
            update_property=True,
            ProvinceModel=Province,
            PropertyModel=Property
        )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0006_alter_property_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="short_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(create_short_code, reverse_func)
    ]
