# Generated by Django 4.1.10 on 2023-10-17 12:42

from django.db import migrations, models
from frontend.utils.organisation import get_abbreviation


def create_short_code(apps, schema_editor):
    Property = apps.get_model('property', 'Property')

    for idx, property_obj in enumerate(Property.objects.all().order_by('id')):
        province = get_abbreviation(property_obj.province.name) if property_obj.province else ''
        organisation = get_abbreviation(property_obj.organisation.name)
        property_name = get_abbreviation(property_obj.name)
        digit = 1000 + idx + 1
        property_obj.short_code = f"{province}{organisation}{property_name}{digit}"
        property_obj.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0006_alter_property_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="short_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(create_short_code, reverse_func)
    ]
