# Generated by Django 4.1.10 on 2023-10-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0007_property_short_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="province",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
