# Generated by Django 4.1.10 on 2023-10-13 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0008_alter_province_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="centroid",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
