# Generated by Django 4.1.10 on 2023-11-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0009_property_centroid"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertytype",
            name="colour",
            field=models.CharField(default="#000000", max_length=20),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_size_ha",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
