# Generated by Django 4.1.10 on 2023-11-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0009_property_centroid"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertytype",
            name="colour",
            field=models.CharField(default="#000000", max_length=20),
        ),
    ]
