# Generated by Django 4.1.10 on 2023-11-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0010_propertytype_colour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_size_ha",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
