# Generated by Django 4.1.10 on 2023-11-15 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stakeholder", "0015_organisation_short_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0010_propertytype_colour_alter_property_property_size_ha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stakeholder.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="property.propertytype"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="property.province"
            ),
        ),
    ]
