# Generated by Django 4.1.13 on 2023-11-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0011_alter_property_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="source_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
