# Generated by Django 4.1.13 on 2024-01-12 04:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0012_parcel_source_parcel_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="boundary",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
