# Generated by Django 4.1.13 on 2024-02-05 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0013_property_boundary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="boundary",
        ),
    ]
