# Generated by Django 4.1.13 on 2024-02-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0014_remove_property_boundary"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="boundary_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("selection", "selection"),
                    ("digitise", "digitise"),
                    ("boundary_file", "boundary_file"),
                ],
                default="selection",
                max_length=255,
                null=True,
            ),
        ),
    ]
