# Generated by Django 4.1.13 on 2024-02-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0015_property_boundary_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="sg_number",
            field=models.CharField(max_length=100),
        ),
    ]
