# Generated by Django 4.1.13 on 2024-02-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0017_propertyoverlaps"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyoverlaps",
            options={
                "verbose_name": "Property Overlaps",
                "verbose_name_plural": "Property Overlaps",
            },
        ),
    ]
