# Generated by Django 4.1.13 on 2024-02-20 09:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0018_alter_propertyoverlaps_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyoverlaps",
            name="overlap_geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
