# Generated by Django 4.1.7 on 2023-06-04 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('stakeholder', '0001_initial'),
        ('swaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='stakeholder.usertitle',
            ),
        ),
    ]
