# Generated by Django 4.1.10 on 2023-10-19 05:49

from django.db import migrations


def assign_organisation_user_to_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    OrganisationUser = apps.get_model('stakeholder', 'OrganisationUser')

    group, _ = Group.objects.get_or_create(name='Data contributor')
    for organisation_user in OrganisationUser.objects.all().distinct('user'):
        organisation_user.user.groups.add(group)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("sawps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extendedgroup",
            options={
                "permissions": [
                    ("can_view_population_trend", "Can view population trend"),
                    ("can_view_population_category", "Can view population category"),
                    ("can_view_property_type", "Can view property type"),
                    ("can_view_density_bar", "Can view density bar"),
                    ("can_view_property_available", "Can view property available"),
                    ("can_view_age_group", "Can view age group"),
                    ("can_view_area_available", "Can view area available"),
                    (
                        "can_view_province_species_count",
                        "Can view province species count",
                    ),
                    (
                        "can_view_province_species_count_as_percentage",
                        "Can view province species count as percentage",
                    ),
                    ("can_view_total_count", "Can view total count"),
                    ("can_view_count_as_percentage", "Can view count as percentage"),
                    ("can_view_population_estimate", "Can view population estimate"),
                    (
                        "can_view_population_estimate_as_percentage",
                        "Can view population estimate as percentage",
                    ),
                ]
            },
        ),
        migrations.RunPython(
            assign_organisation_user_to_group,
            reverse_func
        )
    ]
