# Generated by Django 4.1.10 on 2023-10-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sawps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedGroupPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, unique=True)),
                ("allow_for_organisation_member", models.BooleanField(default=False)),
                ("allow_for_organisation_manager", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="extendedgroup",
            name="permissions",
            field=models.ManyToManyField(to="sawps.extendedgrouppermission"),
        ),
    ]
