# Generated by Django 4.1.10 on 2023-10-27 03:05

from django.db import migrations
from stakeholder.utils import add_user_to_organisation_group


def assign_organisation_user_to_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    OrganisationInvites = apps.get_model('stakeholder', 'OrganisationInvites')
    OrganisationUser = apps.get_model('stakeholder', 'OrganisationUser')

    for organisation_user in OrganisationUser.objects.all():
        add_user_to_organisation_group(
            organisation_user,
            OrganisationInvites,
            Group
        )


class Migration(migrations.Migration):
    dependencies = [
        ("sawps", "0002_alter_extendedgroup_options"),
        ("stakeholder", "0015_organisation_short_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extendedgroup",
            options={
                "permissions": [
                    ("can_view_population_trend", "Can view population trend"),
                    ("can_view_population_category", "Can view population category"),
                    ("can_view_property_type", "Can view property type"),
                    ("can_view_density_bar", "Can view density bar"),
                    ("can_view_property_available", "Can view property available"),
                    ("can_view_age_group", "Can view age group"),
                    ("can_view_area_available", "Can view area available"),
                    (
                        "can_view_province_species_count",
                        "Can view province species count",
                    ),
                    (
                        "can_view_province_species_count_as_percentage",
                        "Can view province species count as percentage",
                    ),
                    ("can_view_total_count", "Can view total count"),
                    ("can_view_count_as_percentage", "Can view count as percentage"),
                    ("can_view_population_estimate", "Can view population estimate"),
                    (
                        "can_view_population_estimate_as_percentage",
                        "Can view population estimate as percentage",
                    ),
                    ("can_view_sampling_report", "Can view sampling report"),
                    ("can_view_province_report", "Can view province report"),
                ]
            },
        ),
        migrations.RunPython(assign_organisation_user_to_group, lambda a, b: None)
    ]
