# Generated by Django 4.1.7 on 2023-05-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='dataUsePermission',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Data use permission',
                'verbose_name_plural': 'Data use permissions',
            },
        ),
    ]
