# Generated by Django 4.1.7 on 2023-05-30 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('stakeholder', '0001_user_model'),
        ('regulatory_permit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataUsePermissionChange',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField()),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='stakeholder.organization',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='stakeholder.userprofile',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Data use permission change',
                'verbose_name_plural': 'Data use permission change',
            },
        ),
    ]
