# Generated by Django 4.1.7 on 2023-06-11 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stakeholder", "0004_alter_organisationrepresentative_organisation_and_more"),
        ("regulatory_permit", "0002_datausepermissionchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datausepermissionchange",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stakeholder.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="datausepermissionchange",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
